version: '3'
services:
  ui:
    restart: always
    build: ./ui
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./ui:/app    
    environment:
      - CHOKIDAR_USEPOLLING=true  
  api:
    restart: always
    build: ./api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app