name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker images
      run: |
        docker-compose -f ${{ github.workspace }}/docker-compose.yml build
        docker-compose -f ${{ github.workspace }}/docker-compose.yml push

    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker-compose build
